profile: local

server:
  shutdown: graceful
  port: 20001
  logging:
    access: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: boiler-template
