profile: test

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: boiler-template
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: local
